### ISSUE TITLE
[bug]:ID用UUID时create函数错误

### ISSUE THREAD

**Issue by suxiaojack** [SpeedPHP/speed#4]
如果数据库表主键ID使用UUID类型，即定义大小为char(36)，非空但默认值是函数UUID()，那么在使用create时，忽略ID插入时，最后PDO驱动内的execute()函数无法正常调用UUID()函数，而是把**UUID()当作字符串**插入到了ID列中。

**Comment by SpeedPHP** [comment]
create是通过键值对的方式插入新记录的，如果需要用mysql函数的高级方式插入数据，请参考手册使用SQL方式插入https://github.com/SpeedPHP/manual/blob/master/%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C-SQL%E6%94%AF%E6%8C%81%E5%8F%8A%E5%85%B3%E8%81%94%E5%AE%9E%E7%8E%B0.md 谢谢。
